config/routes.rb
Rails.application.routes.draw do
  resources :projects
  patch 'drag/project'

  resources :categories
  
  authenticated :user, ->(user) { user.admin? } do
    get 'admin', to: 'admin#index'
    get 'admin/posts'
    get 'admin/comments'
    get 'admin/users'
    get 'admin/show_post/:id', to: 'admin#show_post', as: 'admin_post'
  end
  
  get 'search', to: 'search#index'
  get 'users', to: 'users#profile'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }

  get '/u/:id', to: 'users#profile', as: 'user'

  # Defines the root path route ("/")
  root "pages#home"
  get 'about', to: 'pages#about'
  resources :after_signup
  
  # /posts/1/comments/4
  resources :posts do 
    resources :comments
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html


  
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user, inverse_of: :address
  validates :street, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true
  validates :country, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts, dependent: :destroy

  def self.shedule_category
    Category.create(name: "Schedule at #{Time.now}", display_in_nav: true)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, counter_cache: true
  belongs_to :user

  # for rich text
  has_rich_text :body

  # noticed code
  after_create_commit :notify_recipient
  before_destroy :cleanup_notifications
  has_noticed_notifications model_name: "Notification"

  private

  def notify_recipient
    return if post.user == user
    
    CommentNotification.with(comment: self, post: post).deliver_later(post.user)
  end

  def cleanup_notifications
    notifications_as_comment.destroy_all
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  include Noticed::Model
  belongs_to :recipient, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId

  validates :title, presence: true, length: { minimum: 5, maximum: 50 }
  validates :body, presence: true

  belongs_to :user
  has_many :comments, dependent: :destroy
  belongs_to :category
  
  has_rich_text :body
  has_one :content, class_name: 'ActionText::RichText', as: :record, dependent: :destroy

  # Notifications
  has_noticed_notifications model_name: "Notification"
  has_many :notifications, through: :user

  friendly_id :title, use: %i[slugged history finders]

  def should_generate_new_friendly_id?
    title_changed? || slug.blank?
  end
end

app/models/project.rb
class Project < ApplicationRecord
  has_rich_text :body
  acts_as_list
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :notifications, as: :recipient, dependent: :destroy
  has_one :address, dependent: :destroy, inverse_of: :user, autosave: true

  has_one_attached :avatar

  enum role: %i[user admin]
  after_initialize :set_default_role, if: :new_record?

  # Class level accessor http://apidock.com/rails/Class/cattr_accessor
  cattr_accessor :form_steps do
    %w[sign_up set_name set_address find_users]
  end

  # Instance level accessor http://apidock.com/ruby/Module/attr_accessor
  attr_accessor :form_step

  def form_step
    @form_step ||= 'sign_up'
  end

  with_options if: -> { required_for_step?('set_name') } do |step|
    step.validates :first_name, presence: true
    step.validates :last_name, presence: true
  end

  validates_associated :address, if: -> { required_for_step?('set_address') }

  def full_name
    "#{first_name.capitalize unless first_name.nil?} #{last_name.capitalize unless last_name.nil?}"
  end

  accepts_nested_attributes_for :address, allow_destroy: true

  def required_for_step?(step)
    # All fields are required if no form step is present
    form_step.nil?

    # All fields from previous steps are required if the
    # step parameter appears before or we are on the current step
    form_steps.index(step.to_s) <= form_steps.index(form_step.to_s)
  end

  private

  def set_default_role
    self.role ||= :user
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end

  def posts
    @posts = Post.all.includes(:user)
  end

  def users
  end

  def comments
  end

  def show_post
    @post = Post.includes(:user, comments: [:user, :rich_text_body]).find(params[:id])
  end
end

app/controllers/drag_controller.rb
class DragController < ApplicationController
  def project
    @project = Project.find(drag_project_params[:id])
    @project.insert_at(drag_project_params[:position].to_i + 1)
  end

  private

  def drag_project_params
    params.require(:resource).permit(:id, :position)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[ index show ]
  # GET /posts or /posts.json
  def index
    @posts = Post.includes(:user, :rich_text_body).all.order(created_at: :desc)
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post.update(views: @post.views + 1)
    @comments = @post.comments.includes(:user, :rich_text_body).order(created_at: :desc)

    mark_notifications_as_read
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
     
    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
      redirect_to @post, status: :moved_permanently if params[:id] != @post.slug
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :category_id)
    end

    def mark_notifications_as_read
      if current_user
        notifications_to_mark_as_read = @post.notifications_as_post.where(recipient: current_user)
        notifications_to_mark_as_read.update_all(read_at: Time.zone.now)
      end
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/after_signup_helper.rb
module AfterSignupHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/drag_helper.rb
module DragHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, data: {controller: "emoji-picker"}) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.select :category_id, options_for_select(Category.all.order(name: :asc).collect { |cat| [cat.name, cat.id] }) %>
  </div> 
  
  <%= content_tag(:div, "", class:"pickerContainer", data: {
    emoji_picker_target: "pickerContainer"
  }) %>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.rich_text_area :body, data: { emoji_picker_target: "trixEditor" } %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <h2><%= post.title %></h2>
  <h4>posted by <%= link_to post.user.full_name, user_path(post.user) %></h4>
  <h6><%= pluralize(post.views,"view") %></h6>
  <div>
    <%= post.body %>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="container">
  <h1>Editing post</h1>

  <%= render "form", post: @post %>

  <br>

  <div>
    <%= link_to "Show this post", @post %> |
    <%= link_to "Back to posts", posts_path %>
  </div>
</div>  

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="container">
  <h1>Posts</h1>

  <div id="posts">
    <% @posts.each do |post| %>
      <%= render post %>
      <p>
        <%= link_to "Show this post", post %>
      </p>
    <% end %>
  </div>

  <%= link_to "New post", new_post_path %>
</div>

app/views/posts/new.html.erb
<div class="container">
  <h1>New post</h1>
  <%= render "form", post: @post %>
  <br>
  <div>
    <%= link_to "Back to posts", posts_path %>
  </div>
</div>  

app/views/posts/show.html.erb
<div class="container">
  <%= render @post %>
  <div>
    <%= link_to "Edit this post", edit_post_path(@post) %> |
    <%= link_to "Back to posts", posts_path %>
    <%= button_to "Destroy this post", @post, method: :delete %>
  </div>
</div>  

<div class="container">
  <%= render 'comments/form', post: @post, comment: @post.comments.build, submit_label: "Reply"  %>
  <h2>Comments</h2>
  <% @comments.each do |comment| %>
    <%= render 'comments/comment', post: @post, comment: comment %>
  <% end %>
</div>